#!/usr/bin/env python3
"""
scripts/gen_testing_md.py

Generate TESTING.md from real `go test -json` runs across zenzx's two test
scopes (./pkg/... and the cgo-free headless root package). Scaled down from
the pattern xolu's own gen_testing_md.py uses at a much larger scale (no
coverage-threshold gating, no separate narrative doc to append -- zenzx does
not need either yet) -- but the core idea is the same: the numbers in
TESTING.md come from an actual run, not hand-maintained prose that drifts
out of sync with the real test suite.

Usage:
    python3 scripts/gen_testing_md.py

Writes TESTING.md at the repository root.

Copyright (c) 2026 haitch
Licensed under the Apache License, Version 2.0
"""

import json
import subprocess
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULE_PREFIX = "github.com/ha1tch/zenzx"


def run_json(args, env_extra=None):
    """Run `go test -json <args>`, return the parsed event list."""
    import os

    env = os.environ.copy()
    env.update(env_extra or {})
    proc = subprocess.run(
        ["go", "test", "-json", "-count=1"] + args,
        cwd=ROOT,
        capture_output=True,
        text=True,
        env=env,
    )
    events = []
    for line in proc.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            events.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return events, proc.returncode


def summarise(events):
    """
    Reduce a go test -json event stream to per-package counts.

    Returns dict[pkg] -> {run, pass, fail, skip}, plus a totals dict.
    """
    packages = defaultdict(lambda: {"run": 0, "pass": 0, "fail": 0, "skip": 0})
    totals = {"run": 0, "pass": 0, "fail": 0, "skip": 0}

    for ev in events:
        test = ev.get("Test", "")
        action = ev.get("Action", "")
        pkg = ev.get("Package", "")
        if pkg.startswith(MODULE_PREFIX):
            pkg = pkg[len(MODULE_PREFIX):].lstrip("/")
        if pkg == "":
            pkg = "(root)"

        if test and "/" not in test:  # top-level test only, not a subtest
            if action == "run":
                packages[pkg]["run"] += 1
                totals["run"] += 1
            elif action in ("pass", "fail", "skip"):
                packages[pkg][action] += 1
                totals[action] += 1

    return packages, totals


def main():
    print("Running ./pkg/... (cgo-free)...", file=sys.stderr)
    pkg_events, pkg_rc = run_json(["./pkg/..."], {"CGO_ENABLED": "0"})

    print("Running headless root package (cgo-free, -tags headless)...", file=sys.stderr)
    headless_events, headless_rc = run_json(
        ["-tags", "headless", "."], {"CGO_ENABLED": "0"}
    )

    pkg_summary, pkg_totals = summarise(pkg_events)
    headless_summary, headless_totals = summarise(headless_events)

    version = (ROOT / "VERSION").read_text().strip()
    today = date.today().isoformat()

    grand_total = {
        k: pkg_totals[k] + headless_totals[k] for k in ("run", "pass", "fail", "skip")
    }

    lines = []
    lines.append("# ZenZX Test Suite")
    lines.append("")
    lines.append(f"> Auto-generated by `make testing-md` on {today} for v{version}.")
    lines.append("> Do not edit directly.")
    lines.append(
        "> Both scopes run `CGO_ENABLED=0` -- see the Makefile's own comment "
        "on why that matters for `./pkg/...` specifically."
    )
    lines.append("")
    lines.append("## Test Statistics")
    lines.append("")
    lines.append(f"Version **{version}**, generated {today}.")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("|--------|------:|")
    lines.append(f"| Top-level tests | {grand_total['run']} |")
    lines.append(f"| Passed | {grand_total['pass']} |")
    lines.append(f"| Skipped | {grand_total['skip']} |")
    lines.append(f"| Failed | {grand_total['fail']} |")
    lines.append("")
    lines.append("## Package Breakdown -- `./pkg/...`")
    lines.append("")
    lines.append("| Package | Tests | Skipped | Failed |")
    lines.append("|---------|------:|--------:|-------:|")
    for pkg in sorted(pkg_summary):
        s = pkg_summary[pkg]
        lines.append(f"| `{pkg}` | {s['run']} | {s['skip']} | {s['fail']} |")
    lines.append("")
    lines.append("## Headless root package (`-tags headless`)")
    lines.append("")
    lines.append("| Package | Tests | Skipped | Failed |")
    lines.append("|---------|------:|--------:|-------:|")
    for pkg in sorted(headless_summary):
        s = headless_summary[pkg]
        lines.append(f"| `{pkg}` | {s['run']} | {s['skip']} | {s['fail']} |")
    lines.append("")

    out_path = ROOT / "TESTING.md"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path}", file=sys.stderr)

    if pkg_rc != 0 or headless_rc != 0:
        print("WARNING: one or more test runs failed (see counts above)", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
